# Generated by Django 4.1.7 on 2023-04-27 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000000)),
                ('complete', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 27, 15, 50, 50, 898724))),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
