# Generated by Django 4.1.7 on 2023-04-27 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 27, 15, 55, 41, 891401)),
        ),
    ]
